<?php include '_styles.php'; ?>
<!DOCTYPE html>
<html lang="fr-FR">

  <head>

    <meta charset="utf-8">
    <title><?php echo __('admin.activation_email.subject'); ?></title>

  </head>

  <body>

    <table cellpadding="0" cellspacing="0" border="0" width="100%">
      <tbody>
        <tr><td height="32"></td></tr>
        <tr>
          <td>
            <table
              cellpadding="15"
              cellspacing="0"
              border="0"
              style="<?php echo $css->globalBox; ?>"
              align="center">

              <tbody>

                <tr>
                  <td
                    bgcolor="#f5f5f5"
                    height="80"
                    valign="bottom"
                    style="font-size: 28px; color: #999999; <?php echo $css->fontFamily; ?>">
                    <strong><?php echo AuthBox::cfg('app.name'); ?></strong>
                  </td>
                </tr>

                <tr>
                  <td bgcolor="#fefefe" style="border: 1px solid #dddddd; border-left: none; border-right: none;">
                    <p style="<?php echo $css->p; ?>">Your account on <?php echo AuthBox::cfg('app.name'); ?> has been activated.</p>

                    <p style="<?php echo $css->p; ?>">Enjoy.</p>

                    <p style="margin: 25px 0;">
                      <a
                        href="<?php echo AuthBox::homepageUrl(); ?>"
                        style="padding: 5px 7px; background: #337ab7; border-radius: 3px; color: #ffffff; font-size: 18px; text-decoration: none; <?php echo $css->fontFamily; ?>">
                        Go to <?php echo AuthBox::cfg('app.name'); ?>
                      </a>
                    </p>

                    <p style="<?php echo $css->p; ?>">Cheers.</p>
                  </td>
                </tr>

                <tr>
                  <td
                    bgcolor="#f5f5f5"
                    style="color: #999999; <?php echo $css->fontFamily . ' ' . $css->fontSize; ?>">
                    <em>The <a href="<?php echo AuthBox::homepageUrl(); ?>" style="<?php echo $css->a; ?>"><?php echo AuthBox::cfg('app.name'); ?></a> Team.</em>
                  </td>
                </tr>

              </tbody>

            </table>
          </td>
        </tr>
        <tr><td height="32"></td></tr>
      </tbody>
    </table>

  </body>

</html>