<?php use AuthBox\Lib\Lang; ?>
<!DOCTYPE html>
<html lang="fr-FR">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?php echo __('page.title', ['app_name' => AuthBox::cfg('app.name')]); ?></title>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo $__THEME_URL; ?>/styles.css">

  </head>

  <body>

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li>
            <a
              href="<?php echo AuthBox::cfg('behaviour.homepageUrl'); ?>"
              class="dropdown-toggle"
              data-toggle="tooltip"
              data-placement="bottom"
              title="<?php echo __('nav.back_to_site'); ?>">
              <span class="glyphicon glyphicon-circle-arrow-left" aria-hidden="true"></span>
            </a>
          </li>
        </ul>
        <div class="navbar-header">
          <a class="navbar-brand" href="<?php echo AuthBox::makeUrl('index',
            [
              'after' => $this->p('after'),
              't' => $this->p('t'),
            ]); ?>">
            <?php echo AuthBox::cfg('app.name'); ?>
            <?php if ($baseline = AuthBox::cfg('app.baseline')): ?>
              <small>&nbsp;&ndash;&nbsp; <?php echo $baseline; ?></small>
            <?php endif; ?>
          </a>
        </div>

        <ul class="nav navbar-nav navbar-right">
          <?php if (1): ?>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-flag" aria-hidden="true"></span>
                <?php echo __('languages_label', ['lang' => Lang::getName()]); ?>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <?php foreach (Lang::getLanguages() as $lang): ?>
                  <li<?php echo $lang->code === Lang::getCurrent() ? ' class="active"' : ''; ?>>
                    <a href="<?php echo $lang->url; ?>">
                      <?php echo $lang->name; ?>
                    </a>
                  </li>
                <?php endforeach; ?>
              </ul>
            </li>
          <?php endif; ?>

          <?php if ($__USER): ?>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                <?php echo $__USER->getLogin(); ?>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="<?php echo AuthBox::getLogoutUrl(AuthBox::getAuthUrl()); ?>">
                    <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                    <?php echo __('app.logged_in.logout'); ?>
                  </a>
                </li>
              </ul>
            </li>
          <?php endif; ?>

          <?php if ($__IS_ADMIN): ?>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <?php echo __('admin.nav.title'); ?>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="<?php echo AuthBox::makeUrl('admin'); ?>">
                    <span class="glyphicon glyphicon-dashboard" aria-hidden="true"></span>
                    <?php echo __('admin.nav.panel'); ?>
                  </a>
                </li>
                <li>
                  <a href="<?php echo AuthBox::makeUrl('admin', ['do' => 'logout']); ?>">
                    <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                    <?php echo __('admin.nav.logout'); ?>
                  </a>
                </li>
              </ul>
            </li>
          <?php endif; ?>
        </ul>
      </div>
    </nav>

    <?php include 'flash_messages.phtml'; ?>
