
<?php

  $errors = AuthBox\Lib\Session::delete('login_errors');

?>

<form action="<?php echo AuthBox::makeUrl('login',
  [
    'previous' => AUTHBOX_REQUEST_URL,
    'after' => $this->p('after'),
    't' => $this->p('t'),
  ]); ?>" method="post">

  <div class="panel panel-default">
    <div class="panel-heading"><h3 class="panel-title"><?php echo __('login.panel_title'); ?></h3></div>
    <div class="panel-body">

      <?php if ($errors): ?>
        <div class="alert alert-danger">
          <ul>
            <?php foreach ($errors as $err): ?>
              <li><?php echo $err; ?></li>
            <?php endforeach; ?>
          </ul>
        </div>
      <?php endif; ?>

      <div class="form-group">
        <label for="register-login"><?php echo __('fields.login.label'); ?></label>
        <input
          type="text"
          class="form-control"
          id="register-login"
          name="login"
          placeholder="<?php echo __('fields.login.placeholder'); ?>"
          value="<?php echo htmlentities($__FORM && array_key_exists('login', $__FORM)
            ? $__FORM['login'] : $this->p('login', ''), ENT_COMPAT, 'utf-8'); ?>">
      </div>
      <div class="form-group">
        <label for="register-password"><?php echo __('fields.password.label'); ?></label>
        <input type="password" class="form-control" id="register-password" name="password" placeholder="<?php echo __('fields.password.placeholder'); ?>">
      </div>
      <div class="checkbox">
        <label>
          <input type="checkbox" name="remember" value="1">
          <?php echo __('fields.remember.label'); ?>
        </label>
      </div>
    </div>
    <div class="panel-footer">
      <div class="pull-right">
        <a
          href="#"
          data-toggle="modal"
          data-target="#forgotPasswordModal">
          <?php echo __('login.forgot_password'); ?>
        </a>
        &nbsp; &nbsp;
        <button type="submit" class="btn btn-primary">
          <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          <?php echo __('login.submit_label'); ?>
        </button>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>

</form>

<div class="modal fade" id="forgotPasswordModal" tabindex="-1" role="dialog" aria-labelledby="forgotPasswordModalLabel">
  <form action="<?php echo AuthBox::makeUrl('forgotPassword'); ?>" method="post">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="forgotPasswordModalLabel"><?php echo __('forgot_password.modal.title'); ?></h4>
        </div>
        <div class="modal-body">
          <div class="alert alert-info">
            <?php echo __('forgot_password.modal.info'); ?>
          </div>

          <div class="form-group">
            <label for="forgotPassword-login"><?php echo __('fields.login.label'); ?></label>
            <input
              type="text"
              class="form-control"
              id="forgotPassword-login"
              name="login"
              placeholder="<?php echo __('fields.login.placeholder'); ?>">
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <?php echo __('forgot_password.modal.cancel'); ?>
          </button>
          <button type="submit" class="btn btn-primary">
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
            <?php echo __('forgot_password.modal.apply'); ?>
          </button>
        </div>
      </div>
    </div>
  </form>
</div>