<?php include 'header.phtml'; ?>

<?php

  $errors = AuthBox\Lib\Session::delete('reset_password_errors');

?>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <form action="<?php echo AuthBox::makeUrl('resetPassword', ['token' => $this->p('token')]); ?>" method="post">

        <div class="panel panel-default">
          <div class="panel-heading"><h3 class="panel-title"><?php echo __('reset_password.panel_title'); ?></h3></div>
          <div class="panel-body">

            <?php if ($errors): ?>
              <div class="alert alert-danger">
                <ul>
                  <?php foreach ($errors as $err): ?>
                    <li><?php echo $err; ?></li>
                  <?php endforeach; ?>
                </ul>
              </div>
            <?php endif; ?>

            <div class="alert alert-info">
              <?php echo __('reset_password.info'); ?>
            </div>

            <div class="form-group">
              <label for="register-password"><?php echo __('fields.password.label'); ?></label>
              <input type="password" class="form-control" id="register-password" name="password" placeholder="<?php echo __('fields.password.placeholder'); ?>">
            </div>
          </div>
          <div class="panel-footer">
            <div class="pull-right">
              <button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                <?php echo __('reset_password.submit_label'); ?>
              </button>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>

      </form>

    </div>
  </div>
</div>

<?php include 'footer.phtml'; ?>